### PR TITLE
Konstantin main pull requests

### PR DESCRIPTION
**Pull request by KonstantinHebenstreit**
Updated the Readme for easy access of the explanatory notebooks.

### CODE REVIEW

**Comment by matthias-samwald** [comment]
I suggest putting the notebooks under a seperated sub-header called "Notebooks" rather than "Libraries"

**Review by matthias-samwald — COMMENTED** [review]
I suggest putting the notebooks under a seperated sub-header called "Notebooks" rather than "Libraries" (posting this here as well, just to see if it is logged differently)

**Comment by matthias-samwald** [comment]
Why is one config example given in a comment and another as actual code?

image

**Comment by matthias-samwald** [comment]
What precisely is debug mode doing and how should it be used? Can we create a JSON file (without generations) with debug mode that we can inspect? Perhaps this should be described/demonstrated a bit more.
image

**Comment by matthias-samwald** [comment]
Potential open question after looking at the notebooks: How are API keys (e.g. for accessing OpenAI API) handled?

**Comment by matthias-samwald** [comment]
Maybe rename to more intuitive (?) names:

2_model.ipynb -> 2_generate.ipynb
3_performance.ipynb -> 3_evaluate.ipynbp
(also rename resulting JSON files accordingly)

**Comment by KonstantinHebenstreit** [comment]
After updating main and rebasing this PR now includes all these commits too. I will redo the pull request to keep it simple.

**Pull request closed without merging**
