### PR TITLE
Added licensing information

### PR DESCRIPTION
**Pull request by nomisto**
Adds licensing information from an Enum rather than as free text string. List of licenses is from https://github.com/bigscience-workshop/biomedical/blob/main/bigbio/utils/resources/licenses.json.

### CODE REVIEW

**Comment by matthias-samwald** [comment]
(Looking good!)

**Comment by nomisto** [comment]
Licenses still UNKNOWN

- Asdiv -> https://github.com/chaochun/nlu-asdiv-dataset/issues/2 (Old unanswered issue by Matthias, maybe email them?)
- MedQA -> https://github.com/jind11/MedQA/issues/7 (I opened an issue)

**Comment by matthias-samwald** [comment]
ASDiv is now licensed under  CC BY-NC 4.0

**Comment by nomisto** [comment]
Perfect! This PR would be complete now

**Pull request merged**
