### PR TITLE
Tutorial update

### PR DESCRIPTION
**Pull request by KonstantinHebenstreit**
Restructered the tutorial notebook, putting API at the end. Excluded unnecessary parts. Included full_text_prompt as optional.

### CODE REVIEW

**Comment by matthias-samwald** [comment]
image
Some text in code comments here could be move to markdown cells

**Comment by KonstantinHebenstreit** [comment]
> image Some text in code comments here could be move to markdown cells

yes, I now changed that part to:
image

**Comment by matthias-samwald** [comment]
> Just upload your just downloaded 'worldtree_10.json' file to the web tool.
... sounds a bit weird.

Suggestion:
> Upload the 'worldtree_10.json' file generated in the previous step to the web tool.

Also:
> Next round: Your own data creation with your personal API key.

I don't understand this headline and how it related to the "generate" section before.

**Comment by matthias-samwald** [comment]
@KonstantinHebenstreit Are you still waiting for feedback?

**Pull request merged**
